In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [6]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
np.linspace(0,1,9)

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [9]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [10]:
np.random.rand(9,2)

array([[ 0.81790528,  0.77353808],
       [ 0.57330464,  0.98119314],
       [ 0.15080701,  0.14588693],
       [ 0.67415589,  0.35638243],
       [ 0.79632427,  0.14030658],
       [ 0.76867687,  0.98927849],
       [ 0.22011503,  0.94819901],
       [ 0.94847229,  0.30075215],
       [ 0.61317681,  0.24990365]])

In [14]:
arr = np.arange(25).reshape((5,5))

In [15]:
arr.shape

(5, 5)

In [16]:
arr.dtype

dtype('int64')

In [19]:
a = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
a[:,0]

array([ 5, 20, 35])

In [28]:
a[a%10 ==0]

array([10, 20, 30, 40])

In [30]:
a = np.arange(1,11)

In [31]:
a *a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
a + 1234

array([1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244])

In [33]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766])

In [34]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [37]:
np.remainder(5, a)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])